apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: default
  labels:
    name: redis-master
spec:
  ports:
    - name: redis-port
      nodePort: 30010
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    redis-master: "true"
  type: NodePort

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: default
  labels:
    name: redis-master
spec:
  serviceName: redis-master
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-master
        redis-master: "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: 127.0.0.1:30001/ylf/redis:0.1
        #command: ["sleep"]
        #args: ["100000"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: MASTER
          value: "true"
        - name: REDISPASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: AuthPass
        volumeMounts:
        - name: redis-master-volume
          mountPath: /redis-master-data
        - name: config-path
          mountPath: /redis-master

      volumes:
      - name: redis-master-volume
        hostPath:
            path: /opt/redis/master-data
            type: Directory
      - name: config-path
        configMap:
          name: redis-config
          items:
          - key: master-conf
            path: redis.tmp
