apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: default
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      nodePort: 30011
      targetPort: 6379
  selector:
    app: redis
    type: slave
  type: NodePort
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-slave
  namespace: default
  labels:
    name: redis-slave
spec:
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        type: slave
    spec:
      containers:
      - name: redis
        image: 127.0.0.1:30001/ylf/redis:0.1
        imagePullPolicy: IfNotPresent
        #command: ["sleep"]
        #args: ["9999999"]
        ports:
        - containerPort: 6379
        env:
        - name: REDISPASS
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: AuthPass
        - name: MASTERSVC
          value: redis-master # master service name
        volumeMounts:
        - name: redis-slave-volume
          mountPath: /redis/slave-data
        - name: config-path
          mountPath: /redis/slave-config
      volumes:
      - name: redis-slave-volume
        hostPath:
            path: /opt/redis/slave-data
            type: Directory
      - name: config-path
        configMap:
          name: redis-config
          items:
          - key: slave-conf
            path: redis.tmp
